name: Build and Deploy Packages

on:
  push:
    paths:
      - 'packages/*/**'

jobs:
  detect-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-output.outputs.packages }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of changed packages
      id: get-changes
      run: |
        CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD | grep -o 'packages/[^/]*' | sort | uniq)
        echo "Changed packages: $CHANGED_PACKAGES"
        echo "CHANGED_PACKAGES=$CHANGED_PACKAGES" >> $GITHUB_ENV

    - name: Print changed packages
      run: echo $CHANGED_PACKAGES

    - name: Set output
      id: set-output
      run: |
        PACKAGES=$(echo "$CHANGED_PACKAGES" | sed 's/packages\///g' | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "Packages JSON: $PACKAGES"
        echo "::set-output name=packages::$PACKAGES"

  build:
    runs-on: ubuntu-latest
    needs: detect-packages
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-packages.outputs.packages) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build package
      run: |
        cd packages/${{ matrix.package }}
        npm run build

    - name: Semantic Release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd packages/${{ matrix.package }}
        npx semantic-release
