name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Find changed packages
        id: changed-packages
        run: |
          CHANGED=$(npx lerna changed --json)
          echo "$CHANGED" > changed-packages.json
          echo "changed=$(cat changed-packages.json)" >> $GITHUB_ENV

      - name: Build and publish changed packages
        if: env.changed != '[]'
        run: |
          CHANGED_PACKAGES=$(echo '${{ env.changed }}' | jq -r '.[].name')
          for PACKAGE in $CHANGED_PACKAGES; do
            echo "Building and publishing $PACKAGE"
            cd packages/$PACKAGE
            npm install
            npx semantic-release
            cd ../../
          done

      - name: Clean up npm cache
        run: npm cache clean --force
