name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Find changed packages
        id: changed-packages
        run: |
          CHANGED=$(npx lerna changed --json)
          echo "$CHANGED" | jq -c '.' > changed-packages.json
          echo "CHANGED_PACKAGES=$(cat changed-packages.json)" >> $GITHUB_ENV

      - name: List all packages
        id: list-packages
        run: |
          PACKAGES=$(npx lerna ls --all --json)
          echo "$PACKAGES" | jq -c '.' > all-packages.json
          echo "ALL_PACKAGES=$(cat all-packages.json)" >> $GITHUB_ENV

      - name: Build and publish changed packages
        if: env.CHANGED_PACKAGES != '[]'
        run: |
          CHANGED_NAMES=$(echo '${{ env.CHANGED_PACKAGES }}' | jq -r '.[].name')
          ALL_PACKAGES=$(echo '${{ env.ALL_PACKAGES }}')
          
          for NAME in $CHANGED_NAMES; do
            LOCATION=$(echo $ALL_PACKAGES | jq -r --arg NAME "$NAME" '.[] | select(.name == $NAME) | .location')
            echo "Building and publishing $NAME at $LOCATION"
            cd $LOCATION
            npm install
            npx semantic-release
            cd - > /dev/null
          done

      - name: Clean up npm cache
        run: npm cache clean --force
