name: Publish All Packages

on:
  push:
    branches:
      - main

jobs:
  wait_30_seconds:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Exit successfully
        run: exit 0

  build-and-publish:
    runs-on: ubuntu-latest
    needs: wait_30_seconds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Reset changes
        run: git reset --hard

      - name: Set npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Add scope to package names
        run: node add-scope.js

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add packages/**/package.json
          git commit -m "chore: add scope to package names" || echo "No changes to commit"

      - name: Build packages
        run: npx lerna run build

      - name: Publish packages
        run: npx lerna publish from-package --yes --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get deployment ID
        id: get_deployment_id
        uses: actions/github-script@v6
        with:
          script: |
            const { listDeployments } = require('@octokit/rest')();
            const deployments = await listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: 'development',
              per_page: 1,
              page: 1
            });
            if (deployments.data.length === 0) {
              throw new Error('No deployments found');
            }
            const deploymentId = deployments.data[0].id;
            core.setOutput('deployment_id', deploymentId);

      - name: Set deployment status to success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const deploymentId = core.getInput('deployment_id');
            const { createDeploymentStatus } = require('@octokit/rest')();
            const response = await createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deploymentId,
              state: 'success'
            });
            console.log(response);

      - name: Set deployment status to failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const deploymentId = core.getInput('deployment_id');
            const { createDeploymentStatus } = require('@octokit/rest')();
            const response = await createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deploymentId,
              state: 'failure'
            });
            console.log(response);
