name: Build and Deploy Packages

on:
  push:
    paths:
      - 'packages/*/**'

jobs:
  detect-packages-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the token has write permissions
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Update to Node.js 20

    - name: Get list of changed packages
      id: get-changes
      run: |
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD -- packages | grep -o 'packages/[^/]*' | sort | uniq | sed 's/packages\///' | uniq)
        else
          CHANGED_PACKAGES=$(git diff --name-only $(git hash-object -t tree /dev/null) HEAD -- packages | grep -o 'packages/[^/]*' | sort | uniq | sed 's/packages\///' | uniq)
        fi
        echo "Changed packages: $CHANGED_PACKAGES"
        # Convert space-separated package names to JSON array
        CHANGED_PACKAGES_JSON=$(echo "$CHANGED_PACKAGES" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "CHANGED_PACKAGES_JSON=$CHANGED_PACKAGES_JSON" >> $GITHUB_ENV
        echo "::set-output name=packages::$CHANGED_PACKAGES_JSON"
        echo "Packages JSON: $CHANGED_PACKAGES_JSON"

    - name: Print changed packages
      run: echo $CHANGED_PACKAGES

    - name: Build and Publish npm1drago if changed
      if: contains(steps.get-changes.outputs.packages, 'npm1drago')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd packages/npm1drago
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npx semantic-release

    - name: Build and Publish npm2drago if changed
      if: contains(steps.get-changes.outputs.packages, 'npm2drago')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd packages/npm2drago
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npx semantic-release

    - name: Build and Publish npm3drago if changed
      if: contains(steps.get-changes.outputs.packages, 'npm3drago')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd packages/npm3drago
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npx semantic-release
