name: Build and Deploy Packages

on:
  push:
    paths:
      - 'packages/*/**'

jobs:
  detect-packages-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the token has write permissions
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Update to Node.js 20

    - name: Get list of changed packages
      id: get-changes
      run: |
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- packages)
        else
          CHANGED_FILES=$(git diff --name-only $(git hash-object -t tree /dev/null) HEAD -- packages)
        fi
        echo "Changed files: $CHANGED_FILES"
        CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | grep -o 'packages/[^/]*' | sort | uniq)
        echo "Changed packages: $CHANGED_PACKAGES"
        # Read package names from package.json files
        CHANGED_PACKAGE_NAMES=$(echo "$CHANGED_PACKAGES" | xargs -I {} sh -c 'jq -r ".name" {}/package.json')
        echo "Changed package names: $CHANGED_PACKAGE_NAMES"
        CHANGED_PACKAGE_NAMES_JSON=$(echo "$CHANGED_PACKAGE_NAMES" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "CHANGED_PACKAGE_NAMES_JSON=$CHANGED_PACKAGE_NAMES_JSON" >> $GITHUB_ENV
        echo "packages=$CHANGED_PACKAGE_NAMES_JSON" >> $GITHUB_ENV
        echo "Packages JSON: $CHANGED_PACKAGE_NAMES_JSON"

    - name: Print changed packages
      run: echo $CHANGED_PACKAGE_NAMES

    - name: Build and Publish changed packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        for PACKAGE in $(echo $CHANGED_PACKAGE_NAMES | jq -r '.[]'); do
          PACKAGE_DIR=$(echo $CHANGED_PACKAGES | grep "/$PACKAGE" | head -n 1)
          echo "Building and publishing $PACKAGE in directory $PACKAGE_DIR"
          cd $PACKAGE_DIR
          npm install
          npm run build
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npx semantic-release
          cd - # Go back to the root directory
        done
