name: Build and Deploy Packages

on:
  push:
    paths:
      - 'packages/*/**'

jobs:
  detect-packages-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get list of changed packages
      id: get-changes
      run: |
        CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD | grep -o 'packages/[^/]*' | sort | uniq | sed 's/packages\///' | uniq)
        echo "CHANGED_PACKAGES=$CHANGED_PACKAGES" >> $GITHUB_ENV

    - name: Print changed packages
      run: echo $CHANGED_PACKAGES

    - name: Build and Publish npmone if changed
      if: contains(env.CHANGED_PACKAGES, 'npmone')
      run: |
        cd packages/npmone
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npx semantic-release

    - name: Build and Publish npmtwo if changed
      if: contains(env.CHANGED_PACKAGES, 'npmtwo')
      run: |
        cd packages/npmtwo
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npx semantic-release

    - name: Build and Publish npmthree if changed
      if: contains(env.CHANGED_PACKAGES, 'npmthree')
      run: |
        cd packages/npmthree
        npm install
        npm run build
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npx semantic-release
